spring:
  application:
    name: auth
  config:
    import: "optional:configserver:"
  datasource:
    url: jdbc:mysql://localhost:3306/naver_land_auth?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 9001